### ISSUE TITLE
Style API tests

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-test-suite#76]
Alongside render and query tests, add a third type of test: Style API tests. These tests should be written in terms of a sequence of abstract Style API commands. As a starting point for commands, look to [the diff implementation in mapbox-gl-style-spec](https://github.com/mapbox/mapbox-gl-style-spec/blob/mb-pages/lib/diff.js).

gl-js and gl-native harnesses for Style API tests would start with a blank map, execute the sequence of commands, render the result, and compare it to a reference image as with render tests.

Obviously for gl-native this depends on actually _having_ a [Style API](https://github.com/mapbox/mapbox-gl-native/issues/837) and node bindings that expose it.

**Comment by jfirebaugh** [comment]
Above linked issues should have regression tests of this type.

**Comment by lucaswoj** [comment]
I'm envisioning a syntax along the lines of this: 

```json
{
  style: {
    metadata: {
      operations: [
        ['waitUntilFrame']
        ['setPaintProperty', 'water', 'fill-pattern', 'harbor-15']
      ]
    }
  }
}
```

When an array of operations are specified in the style metadata, they are executed sequentially before the "actual" image is captured. This format allows for GL JS and GL Native implementations. Operations include all style API methods (`setPaintProperty`, `setLayoutProperty`, `addLayer`, ...) as well as some special operations (`waitUntilFrame`)

# Next Steps 

 - [ ] support style API tests for GL JS
 - [ ] support style API tests for GL Native (blocked on the style API merging)
 - [ ] create some basic tests 
 - [ ] create regression test for mapbox/mapbox-gl-js#2550
 - [ ] create regression test for mapbox/mapbox-gl-js#2534
 - [ ] create regression test for mapbox/mapbox-gl-js#2486
 - [ ] create regression test for mapbox/mapbox-gl-js#2477

**Comment by jfirebaugh** [comment]
👍 

The `waitUntilFrame` command exists to force the computation of state that's calculated lazily at render time?

**Comment by lucaswoj** [comment]
@jfirebaugh Right. Some bugs aren't triggered unless two mutations aren't separated by that computation of state that's calculated lazily at render time. Some bugs are only triggered if they _aren't_ separated.
